#!/usr/bin/env bash
# 1. Run Nginx as Nginx

# Ensure Nginx is not running
sudo service nginx stop

# give permission to work on nginx.conf 
sudo chmod 600 /etc/nginx/nginx.conf

#backup of your configuration file before running any in-place (-i) modifications to avoid accidental data loss.
sudo cp /etc/nginx/nginx.conf /etc/nginx/.nginx.conf

# Update Nginx configuration to run as nginx user
sed -i '1s/^.*user.*$/user nginx;/' /etc/nginx/nginx.conf

# Update file and directory permissions
sudo chown -R nginx:nginx /var/lib/nginx
sudo chown -R nginx:nginx /var/log/nginx
sudo chmod 444 /etc/nginx/nginx.conf

# delete the sites-enabled default file if there
sudo rm /etc/nginx/sites-enabled/default
# give permissions
sudo chmod 775 /etc/nginx/sites-available/default
# nginx must be listening on all active IPs on port 8080
sudo -u nginx sed -i -e 's/listen\s*80;/listen 8080;/' -e 's/listen \[::\]:80 ipv6only=on;/listen [::]:8080 ipv6only=on;/' /etc/nginx/sites-available/default

# linking the sites-available default file to the sites-enabled directory
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# restart nginx server with nginx username
sudo -u nginx service nginx restart
