#!/usr/bin/env bash
# 1. Run Nginx as Nginx

# Ensure Nginx is not running
sudo service nginx stop

# give permission to work on nginx.conf 
sudo chmod 600 /etc/nginx/nginx.conf

#backup of your configuration file before running any in-place (-i) modifications to avoid accidental data loss.
sudo cp /etc/nginx/nginx.conf /etc/nginx/.nginx.conf

# Update Nginx configuration to run as nginx user
sed -i '1s/^.*user.*$/user nginx;/' /etc/nginx/nginx.conf

# Update file and directory permissions
sudo chown -R nginx:nginx /var/lib/nginx
sudo chown -R nginx:nginx /var/log/nginx
sudo chmod 444 /etc/nginx/nginx.conf

# restart nginx server with nginx username
sudo -u nginx service nginx restart
