#!/usr/bin/env bash
# Nginx must be running, and listening on port 80 of all the server
# active IPv4 IPs
rm /etc/nginx/sites-enable/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enable/
sudo service nginx restart
curl -i 0:80
