#!/usr/bin/env bash
# Nginx must be running, and listening on port 80 of all the server
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/ || sudo service nginx start
curl -i 0:80
sudo service nginx stop
