#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.
echo -e "ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/\nsudo service nginx restart\ncurl -i 0:80" > 3
bash 3
sudo service nginx stop
