#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.
(bash <(echo -e "ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/\nsudo service nginx restart\nsleep 10\nsudo service nginx stop") & disown) > /dev/null 2>&1 < /dev/null
