#!/usr/bin/env bash
# Web servers are the piece of software generating and serving HTML pages, let’s install one!
sudo mkdir -p /var/www/html
sudo touch /var/www/html/index.html
sudo chown -R $USER:$USER /var/www/html
echo "\[\"Holberton School\"\]" >> /var/www/html/index.html
# sudo nginx -t
